### ISSUE TITLE
Skript Reflect fails to load on version 1.20.6

### ISSUE THREAD

**Issue by CheeseTroll** [SkriptLang/skript-reflect#111]
**Describe the bug**
The server is unable to load the latest release of Skript-Reflect on Paper 1.20.6 with Skript 2.8.6

**To reproduce**
1) Change server version to 1.20.6
2) Install Skript-Reflect
3) Restart Server & Check console for errors

**Expected behavior**
I expect Skript-Reflect to work on version 1.20.6

**Screenshots**
Console error: https://pastebin.com/raw/J98z7eMQ 

**Server information**
- skript-reflect: 2.4-beta1
- Skript: 2.8.6
- Bukkit: Paper 1.20.6
- Minecraft: Feather Client 1.20.6
- Java: N/A
- OS: N/A

**Additional context**

**Comment by sovdeeth** [comment]
This is not the latest version of skript-reflect
Please download 2.4 from the releases tab.
