### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by SpaceboiX** [SkriptLang/skript-reflect#118]
**Describe the bug**
Unsure.

**To reproduce**
```
import:
  io.th0rgal.oraxen.api.OraxenItems

expression orax[en] item <from|of> %string%:
  get:
    return OraxenItems.getItemById(expr-1).build()

on right click:
  drop 1 of oraxen item of "blueSlimeball" at event-location
```

**Expected behavior**
Drop a 'blueSlimeball' from the Oraxen plugin

**Error**
https://pastebin.com/f9gzy2Vv

**Server information**
- skript-reflect: 2.5.1
- Skript: 2.9.0
- Bukkit: 
- Minecraft: 1.20.4
- Java: 21
- OS: Windows 10 10.0 (amd64)

**Comment by NotSoDelayed** [comment]
Try `orax[en] item (from|of) %string%`

**Comment by sovdeeth** [comment]
Doesn't seem like a skript-reflect issue. The issue is that org.bukkit.inventory.ItemRarity doesn't exist on 1.20.4.
