### ISSUE TITLE
No matching method with this fork

### ISSUE THREAD

**Issue by AzonFR** [SkriptLang/skript-reflect#23]
I've try your fork because you fixed a lot of bugs but i have an error when i use a method from FactionsX plugin (i don't try other plugins), which I don't have with the latest version of btk5h https://github.com/btk5h/skript-mirror/releases/tag/v1.0.0

Script: https://gyazo.com/d05a2e93af26fffc017a294c3602aeb5
Error (i try 5-6 versions https://github.com/TPGamesNL/skript-mirror/actions) (the latest and other): https://gyazo.com/c3bfb9f1e9500344c4815b89c43b68c0
With btk5h skript-mirror 1.0, i have no error: https://gyazo.com/7f959a91756c7a10b3a7077cfd8d430d
There is no error on startup

- Skript: 2.2-dev36
- Bukkit: PaperSpigot 1.8.8
- Java: 8
- OS: Ubuntu 18.04

**Comment by TPGamesNL** [comment]
This is probably because since skript-mirror 2.0.0, fields, such as `PlayerManager.INSTANCE`, no longer require the exclamation mark (`!`), so you need to use `PlayerManager.INSTANCE.getFPlayer("%{_p}%")`.

**Comment by AzonFR** [comment]
Exact, it work fine ! Thanks for all fix you made (https://github.com/btk5h/skript-mirror/issues/154 for example)

**Comment by TPGamesNL** [comment]
You're welcome :)
