### ISSUE TITLE
Looks like event priorities don't work

### ISSUE THREAD

**Issue by AzonFR** [SkriptLang/skript-reflect#24]
Priorities when listening an event don't work, i listen to the BlockBreak event like this: https://gyazo.com/5080559a7ce06ad80d7919513816522a
Normally the broadcast of skript-mirror should be after that of skript? because the priority is highest and skript is normal: https://gyazo.com/63d0e6c4a051514d5aab5e01ab1d1e56

Same with worldguard, when the event is cancelled and it use a priority less than highest but the broadcast is before skript-mirror: https://gyazo.com/e22b5ce5e01d8c646f7ef547fa464368

**Comment by TPGamesNL** [comment]
Have you tried priority lowest? It seems to work for me:
```
on break:
	broadcast "skript evt"

on all BlockBreakEvent with priority lowest:
	broadcast "mirror[lowest] evt"

on all BlockBreakEvent with priority highest:
	broadcast "mirror[highest] evt"
```
![image](https://user-images.githubusercontent.com/29547183/86812300-27d6f580-c07f-11ea-80b1-baaab258c476.png)

**Comment by AzonFR** [comment]
you mean lowest priority > highest ? i try next time and i tell you

**Comment by TPGamesNL** [comment]
Yes, see [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/EventPriority.html):
![image](https://user-images.githubusercontent.com/29547183/86814042-2c9ca900-c081-11ea-85be-917ccbe10be5.png)

**Comment by AzonFR** [comment]
Ouchh i don't know, now it work, thanks
