### ISSUE TITLE
better syntax for custom event selection

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/skript-reflect#25]
Currently, custom events require a `name` entry to be used for calling the event, but this doesn't look great. An idea would be to base it off the syntax, but that won't be a good solution when your syntax becomes more complex.
Any suggestions are welcome

**Comment by TPGamesNL** [comment]
solved:
```
[local] [custom] event %string%: # <- name is now here
	patterns: # list of patterns, required
		# patterns
	event-values: # list of types, optional
	parse:
		# code, optional
	check:
		# code, required
```
will also add a `pattern: #pattern` as an entry, not a section

**Comment by Moderocky** [comment]
If possible, I think we should add a built-in section to tie this to an existing Bukkit event, perhaps with a `class[es]` section.

I'm imagining something like:
```
[local] [custom] event %string%: # <- name is now here
	patterns: # list of patterns, required
		# patterns
        classes:
                org.bukkit.event.YourEvent # will make this behave the same as using "on YourEvent:"
	event-values: # list of types, optional
	parse:
		# code, optional
	check:
		# code, required
```

**Comment by TPGamesNL** [comment]
At first I wasn't sure about where to initialize event-values and extra data with the `classes` section, now I think there are 2 possibilities:
1. Have an expression like `event-caller` / `calling event` which can be used in the check section to set event-values and extra data.
2. Have a `prepare` section or something alike where the event-values and extra data are set, with the `event` expression. This section will only be run if the event was called by an event in the `classes` section.

Also maybe use `event classes` instead of `classes`

**Comment by TPGamesNL** [comment]
> At first I wasn't sure about where to initialize event-values and extra data with the `classes` section, now I think there are 2 possibilities:
> 
> 1. Have an expression like `event-caller` / `calling event` which can be used in the check section to set event-values and extra data.
> 2. Have a `prepare` section or something alike where the event-values and extra data are set, with the `event` expression. This section will only be run if the event was called by an event in the `classes` section.
> 
> Also maybe use `event classes` instead of `classes`

Nvm not doing that, as it can easily be done in a seperate trigger
