### ISSUE TITLE
BlockBreakEvent not working correctly

### ISSUE THREAD

**Issue by altruiis** [SkriptLang/skript-reflect#32]
**Describe the bug**
I have a BlockBreakEvent that should add to a variable everytime the block is broken and the person is in a town. However, sometimes it adds two to the variable despite only breaking the block once. Some ores don't even work at all.

Code: https://hastebin.com/uracawofut.sql

**To reproduce**
1. Install skript-reflect and Skript
2. Write the event pasted above
3. Some ores add to the variable twice, some not at all.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/71913030/103112308-5767c300-4609-11eb-9cee-8f697c90ae6f.png)
Iron ore does it twice, lapis does it once (which is how they should all function) and gold ore does not even function whatsoever.

**Server information**
- skript-reflect: 2.1.0
- Skript: 2.5.3
- Bukkit: 1.16.4
- Minecraft: 1.16.4
- Java: 8
- OS: ?

**Additional context**

**Comment by TPGamesNL** [comment]
Can you add a broadcast at the top of the trigger, to debug

**Comment by altruiis** [comment]
> 
> 
> Can you add a broadcast at the top of the trigger, to debug


![image](https://user-images.githubusercontent.com/71913030/103143982-61a3c300-46d6-11eb-9f8d-2cd2cd73443d.png)
Lapis still does it once, so it works properly for that block
![image](https://user-images.githubusercontent.com/71913030/103143985-708a7580-46d6-11eb-9222-518d0dc7d083.png)
Iron ore only broadcasts once, but it adds to the variable twice?
![image](https://user-images.githubusercontent.com/71913030/103143987-7da76480-46d6-11eb-9ec1-25f883f91f45.png)
Gold ore does not add to the variable, but it still broadcasts the message.
![image](https://user-images.githubusercontent.com/71913030/103144006-c19a6980-46d6-11eb-8882-33e454398d9f.png)
Coal ore broadcasts once and then adds to the variable _three_ times, but none of them broadcast twice, they all broadcast once.

**Comment by TPGamesNL** [comment]
I recommend using `else if`'s instead of `if`'s if you chain them like that

**Comment by altruiis** [comment]
Weird, it seems to be working now when I haven't modified the file at all. All ores only add to the variable once. No clue what the issue was but I guess I can close this now. Thank you!

**Comment by TPGamesNL** [comment]
You're welcome :D
