### ISSUE TITLE
Sk reload all gives errors but reloading the skripts separately works

### ISSUE THREAD

**Issue by ghost** [SkriptLang/skript-reflect#33]
**Describe the bug**

When I execute /sk reload all when applying a custom public expression to a Skript, Skript doesn't recognize it. This is the bug because normally, Skript would recognize the expression.

**Expected behavior**

I expected the skript to give no errors when reloading all the Skripts with /sk reload all. Instead, the Skript gave errors but when the Skripts were reloaded separately they suddenly worked. I ended up having to make a bunch of on skript events with "make console execute command "/sk reload duel" etc. so that the skripts could be reloaded separately.

**Screenshots**
https://user-images.githubusercontent.com/63815615/103445671-640d9c00-4c45-11eb-8826-8e66ef90aa30.mp4

**Server information**
- skript-reflect: 2.2alpha2 (tried in 2.1.0 as well)
- Skungee: 2.0.0
- Skript - 2.5.3
- This server is running Paper version git-Paper-337 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by TPGamesNL** [comment]
So you have 2 scripts:
- duel.sk
- gamemode.sk

In which of those scripts do you have the `without itemflags` expression (I presume it's that expression you're talking about)?
Also, please fill in the skript-reflect and Skript version.

**Comment by ghost** [comment]
Updated the skript and skript-reflect versions.
![global - Notepad 1_3_2021 12_37_30 AM (1)](https://user-images.githubusercontent.com/63815615/103472496-4da63400-4d5c-11eb-98ff-a22521212988.png)
I have the expression in my 3rd skript, "global.sk", and yes that is the expression.

**Comment by TPGamesNL** [comment]
Skript loads files and triggers in a logical order, files alphabetical, triggers within that file from top to bottom. Script starts loading with duel.sk and gamemode.sk, and only then global.sk is loaded. So in the first 2 scripts, the `without itemflags` syntax doesn't exist yet. You can fix this by either renaming the global.sk file to be loaded first, or by enabling preloading in skript-reflect's config (the preloading feature was made for this exact issue).

**Comment by ghost** [comment]
Thank you so much that really helped!
