### ISSUE TITLE
Async section returns <none>

### ISSUE THREAD

**Issue by Bartek200219** [SkriptLang/skript-reflect#36]
**Describe the bug**
Async section returns <none>

**To reproduce**
Copy paste this code  (it's example from gitbook with command trigger)
```
command /testy:
	trigger:
		set {_i} to 2
		create new section with {_x} stored in {_section}:
			return {_x} * {_i}
		run section {_section} async with 3 and store result in {_result} and wait
		broadcast "Result: %{_result}%"
```

**Expected behavior**

**Screenshots**
![screenshot](https://i.imgur.com/6GvlB9t.png)
**Server information**
- skript-reflect:2.2.1
- Skript:2.5.3
- Bukkit:git-Paper-505
- Minecraft:1.16.5
- Java:1.8.0_271
- OS:Windows

**Additional context**

**Comment by TPGamesNL** [comment]
This has been fixed in https://github.com/TPGamesNL/skript-reflect/commit/a6a4541f439e7cc5bf1c6782f4ee422ed7f42e6e, you can download it here: https://github.com/TPGamesNL/skript-reflect/actions/runs/621414100
