### ISSUE TITLE
Consider adding api-version 1.13

### ISSUE THREAD

**Issue by TheDGOfficial** [SkriptLang/skript-reflect#37]
**Is your feature request related to a problem? Please describe.**
```
[04:46:16 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[04:46:27 WARN]: Legacy plugin skript-reflect v2.2.1 does not specify an api-version.
```

**Describe the solution you'd like**
Add api-version: 1.13 to plugin.yml of the plugin.

**Describe alternatives you've considered**
Leave it as-is, but not future proof. Future versions may refuse to load plugins with no api-version, however that is also the case with api-version 1.13 - a future version may require a higher api version to load or not give warnings. Basically, adding api-version hops you into Spigot's decisions, but not adding it is not a solution.

**Additional context**
Adding this will disable legacy plugin bytecode rewrite made by Spigot. This may throw NoSuchFieldError's on runtime even though it compiles fine if the code uses Material enum values, or such that Spigot rewrites. However this not the case mostly since Skript has aliases and Skript had api-version for a long time.

Note: Adding this to plugin.yml will not affect < 1.13. In < 1.13, the entry will just be ignored. This will only have an effect on 1.13+, so adding this will not make the plugin incompatible with < 1.13, however, if you use another value, such as, api-version: 1.14, then it will not work on 1.13.

**Comment by TPGamesNL** [comment]
The main reason I initially didn't have this, because I read that support for api-version 1.13 would end eventually, but since this plugin mainly depends on Skript, I'll just follow them :)
