### ISSUE TITLE
IllegalPluginAccessException when using EvtByReflection for non-event classes

### ISSUE THREAD

**Issue by FranKusmiruk** [SkriptLang/skript-reflect#39]
**Describe the bug**
As the title says, an IPAE is thrown when a class that doesn't implement Event is used as input.

**To reproduce**
```
import:
  java.util.function.Consumer


on Consumer:
  broadcast "%event%"
```
**Expected behavior**
I would expect the addon to do type-checking before casting or passing around the input, and throw an error if applicable.

**Comment by TPGamesNL** [comment]
Fixed in https://github.com/TPGamesNL/skript-reflect/commit/8e024e256f0cb92238dfcde3a525ef3650271231
