### ISSUE TITLE
Suggestion: Class Cast

### ISSUE THREAD

**Issue by 0XPYEX0** [SkriptLang/skript-reflect#40]
For example, in Java:
int a = 1;
Long b = (Long) a;

Can the provider be implemented in skript-reflect?
Thanks a lot.

**Comment by TPGamesNL** [comment]
skript-reflect does this automatically. Can you show where you'd need this?

**Comment by 0XPYEX0** [comment]
set {_p} to "just_a_example" parsed as player
set {_w} to {_p}.getLocation().getWorld().getHandler()

{_w} is a WorldServer now.But I need NMS World
They are same acturally

**Comment by TPGamesNL** [comment]
A WorldServer is an NMS World tho: 
![image](https://user-images.githubusercontent.com/29547183/115026024-4a295980-9ec2-11eb-9333-806c21388b02.png)

**Comment by 0XPYEX0** [comment]
Yeah, they are same, but when I try to put {_w} into a Java function, not of the same type

**Comment by TPGamesNL** [comment]
It it a World, you're probably doing something wrong there.

**Comment by 0XPYEX0** [comment]
It told me that WorldServer is not World, but they are same

**Comment by TPGamesNL** [comment]
Anyway, this place is for suggestions/bug reports, if you want help with your scripts, I recommend you join the [skript-reflect Discord](https://discord.gg/jDW8UbD) or [skUnity Discord](https://discord.gg/q7UM6vJ)
