### ISSUE TITLE
Skript-reflect not working on 1.17?

### ISSUE THREAD

**Issue by fredagsguf** [SkriptLang/skript-reflect#41]
I was told on the skript github that this is a skript-flect issue.
https://github.com/SkriptLang/Skript/issues/4130

### Description

Skript-reflect not working on 1.17? :/

### Steps to Reproduce

Not sure how exactly to reproduce this as i'm not sure the cause of it.

### Expected Behavior

That it worked? xD

### Errors / Screenshots

https://mclo.gs/5ON1Y0Y

### Server Information
* **Server version/platform:** Purpur1206 
* **Skript version:** Skript-alpha1 (I've also tried latest "Action" builds 
* **Skript-reflect:** latest stable release version 2.2.1

**Comment by TPGamesNL** [comment]
For skript-reflect, you should also use the latest action build: https://github.com/TPGamesNL/skript-reflect/actions

**Comment by fredagsguf** [comment]
Seems to have done the trick, thank you ^^
