### ISSUE TITLE
1.17 Stack trace when using a non-existent event

### ISSUE THREAD

**Issue by Phe0X** [SkriptLang/skript-reflect#42]
**Describe the bug**
Having an event that doesn't exist (such as "on test:") in a Skript print a stack trace (skript severe error, can be found here https://pastebin.com/b6smGqL5). I found out that the same issue occurs when trying to use an event from skript-packet (on packet event %packettype%:) which is a huge problem for me but I don't know if it happens with other addons

**To reproduce**
Start a new paper 1.17 server with Skript 2.6 b1, create a new skript with an event that doesn't exist, such as "on test:", reload it and see the stack trace

**Expected behavior**
Shouldn't print a stack trace but should print the errors found in the script (and it shouldn't print it when trying to use an event from skript-packet too)

**Screenshots**
Not needed here, but can provide if you really need some

**Server information**
- skript-reflect: 2.2.1
- Skript: 2.6-beta1
- Bukkit: git-Paper-68
- Minecraft: 1.17
- Java: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9)
- OS: Windows 10
Tested with no scripts (just the 2 lines one to make it print the stack trace) and no other plugins 

**Additional context**
I have no idea how addons are made, but maybe this occurs with skript-packet because every event are not registered (because of the number of packets), but this is pure dumb speculation from me.
Sorry if my english isn't perfect, it isn't my main language but I tried my best haha

**Comment by TPGamesNL** [comment]
You need to use the latest action build for Skript 2.6: https://github.com/TPGamesNL/skript-reflect/actions

**Comment by Phe0X** [comment]
Oh thanks it works ! Sorry for not checking earlier, forgot actions were a thing ! Have a great day :)

**Comment by TPGamesNL** [comment]
No problem \:D
