### ISSUE TITLE
Can not parse Java Array correctly

### ISSUE THREAD

**Issue by 0XPYEX0** [SkriptLang/skript-reflect#44]
**Describe the bug**
Java Array can not parse as Skript Array correctly
It will have the only one element

**To reproduce**
set {_array::"all"} to [{_javaArray}]
send "%size of {_array::"all"}%" to console
//It will be always 1
//
loop {_array::"all"}:
    send "%loop-value%" to console
//It will be "[%all elements to string%]"
//_Do not care about the "all", because "*" will be recognized as an special mark_

**Expected behavior**
No

**Screenshots**
No

**Server information**
- skript-reflect: 2.2.3
- Skript: 2.5.3
- Bukkit: Spigot-1.16.5
- Minecraft: 1.16.5
- Java:  1.8.0-292
- OS: Windows10

**Additional context**
No

**Comment by TPGamesNL** [comment]
You're using the wrong expression: `[%objects%]` is for turning a Skript list into a Java array, but `...%object%` is for turning a Java array into a Skript list

**Comment by 0XPYEX0** [comment]
Okay, Thanks a lot.I'm such a fool haha
