### ISSUE TITLE
Parsing not implemented (remember to override parse method)

### ISSUE THREAD

**Issue by ghost** [SkriptLang/skript-reflect#45]
**Describe the bug**
I don't know why but between version 2.2.2 and 2.2.3 my skript doesn't work anymore and I am 100% sure that the error comes from SK-REFLECT

**To reproduce**
The skript is as follows: 

`on chat:
	set {roleicachat.%player%} to group of player
	if {tchatskycdica.%player%} is not set:
		set {_messmot::*} to {messagenew.%player%} split at " "
		loop {_messmot::*}:
			if loop-value contain "<chat=":
				remove "%{_messmot::%loop-index%}%" from {_messmot::*}
		loop {_messmot::*}:
			if loop-index = "1":
				set {messagenew2.%player%} to "%{_messmot::1}%"
			else:
				set {messagenew2.%player%} to "%{messagenew2.%player%}% %{_messmot::%loop-index%}%"
		if {messagenew.%player%} is not set:
			send "**[%{roleicachat.%player%}%] %player% **➜ %message%" to channel with id "510293782944808970"
		else:
			if {messagenew2.%player%} contain "@here" or "@everyone":
				replace all "@here" with "@ here" in {messagenew2.%player%}
				replace all "@everyone" with "@ everyone" in {messagenew2.%player%}
				send "**[%{roleicachat.%player%}%] %player% **➜ %{messagenew2.%player%}%" to channel with id "510293782944808970"
			else:
				send "**[%{roleicachat.%player%}%] %player% **➜ %{messagenew2.%player%}%" to channel with id "510293782944808970"
	set {tchatskycdica.%player%} to 1
	wait 2 tick
	delete {tchatskycdica.%player%}
	delete {messagenew2.%player%}`

**Server information**
![image](https://user-images.githubusercontent.com/12047619/129326052-ef147a20-08a7-4592-9933-c5a46bb5f443.png)
Java 16
Spigot : 1.16.5

**Additional context**
Log error : 
https://pastebin.com/SnhNWwPD
Error is with Sk-reflect 2.2.3 now when i use 2.2.2 no error :\

**Comment by TPGamesNL** [comment]
This exception is not caused by skript-reflect
