### ISSUE TITLE
There is an import bug...?

### ISSUE THREAD

**Issue by 0XPYEX0** [SkriptLang/skript-reflect#47]
**Describe the bug**
When I reload the skript, the exception happened

**To reproduce**
Execute Skript reload command, then it happened

These are my codes:
```
import:
	com.meowj.langutils.lang.LanguageHelper
on swap items:
	if player is sneaking:
		set {_p} to player
		set {_b} to target block of {_p}
		set {_type} to {_b}.getType()
		set {_localeType} to LanguageHelper.getMaterialName({_type}, {_p})
		send action bar "&a你看向的方块是:&f %{_localeType}%" to {_p}
```

**Expected behavior**
Reload normally

**Screenshots**
No

**Server information**
- skript-reflect: 2.2.3
- Skript: 2.6
- Bukkit: 1.18.1-R0.1-SNAPSHOT
- Minecraft: 1.18.1
- Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39)
- OS: Linux amd64 3.10.0-1160.25.1.el7.x86_64

**Additional context**
This is error log: https://paste.ubuntu.com/p/v2TCwnbbB9/

**Comment by TPGamesNL** [comment]
Can you send the jar file with that imported class in it?

**Comment by 0XPYEX0** [comment]
[LangUtils-3.2.3.jar.zip](https://github.com/TPGamesNL/skript-reflect/files/7877243/LangUtils-3.2.3.jar.zip)
unzip it

**Comment by TPGamesNL** [comment]
That plugin isn't made for your server version, it depends on server classes that aren't present in 1.18. This makes it so the classes aren't really accessible anymore reflectively, so skript-reflect throws an exception (#20)

You should update that plugin to get a version that supports your server version
