### ISSUE TITLE
Imports no longer work in effect commands

### ISSUE THREAD

**Issue by abandonedaccount6235** [SkriptLang/skript-reflect#48]
**Describe the bug**
In the last version of skript-mirror, [you could run import from effect commands.](https://github.com/TPGamesNL/skript-reflect/blob/ec386fbcc7a3f7ac7c4c027f0e9abb1becd9f25c/src/main/java/com/btk5h/skriptmirror/skript/custom/CustomImport.java#L170-L180) This functionality seems to have been lost at some point in skript-reflect.

**To reproduce**
Try running `import com.whatever.Class` in an effect command. It will error.

**Expected behavior**
Importing is possible via effect commands. This enables quick tests.

**Additional context**
It seems this may have been removed intentionally by 272078ca68c4e661b71940604b25f41ee4a9583c, but I'm not sure

**Comment by TPGamesNL** [comment]
I don't remember exactly why I removed it at the time, but I do no that I used the class expression multiple times since in effect commands and it would've been more convenient to use an import. I'll also make sure to add docs for this, since it was undocumented before.

**Comment by TPGamesNL** [comment]
Implemented in https://github.com/TPGamesNL/skript-reflect/commit/344c4730776d078f58fdbbdb592f86ae679be8b0
