### ISSUE TITLE
Event priority error

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/skript-reflect#50]
**Describe the bug**
Gives error when you try to use event priority with imported event.

**To reproduce**
You can use the given example on the wiki:
```
import:
  org.bukkit.event.entity.EnderDragonChangePhaseEvent

on EnderDragonChangePhaseEvent with priority highest:
  # your code
```

**Expected behavior**
no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/59025999/162620231-298856e1-2d74-4fb6-8ad6-534d0ef6f26c.png)

**Server information**
- skript-reflect: 2.3
- Skript: 2.6.1
- Bukkit: 1.18.2 (Purpur)
- Minecraft: 1.18.2
- Java: 17
- OS: Centos 7

**Comment by TPGamesNL** [comment]
Forgot to commit my code for this when https://github.com/SkriptLang/Skript/pull/4502 was merged, should be fixed now, try the latest Actions build
