### ISSUE TITLE
Usage of imported classes in effect commands

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/skript-reflect#51]
**Is your feature request related to a problem? Please describe.**
Title is explaining almost everything. That would be awesome if we can use imported classes in skript's effect commands.

**Describe the solution you'd like**
`!send Bukkit.getServer()`
`!send SomePluginAPI.chargeXYZ(1, 5, -9)`

**Comment by TPGamesNL** [comment]
This was added in the latest release: https://tpgamesnl.gitbook.io/skript-reflect/basics/importing-classes#importing-in-effect-commands

**Comment by UsainSrht** [comment]
Sorry my bad
