### ISSUE TITLE
This event doesn't support event priority

### ISSUE THREAD

**Issue by MisterLolxd2** [SkriptLang/skript-reflect#52]
**Describe the bug**
The events with priority doesn't work:
(imports: org.bukkit.event.block.BlockBreakEvent and org.bukkit.event.block.BlockPlaceEvent)
on BlockBreakEvent with priority monitor:
on all BlockPlaceEvent with priority monitor:
The errors:
[Skript] Line 257: (drop.sk)
    This event doesn't support event priority
    Line: §7on BlockBreakEvent with priority monitor:
 
[22:51:46 ERROR]: [Skript] Line 5: (preventjump.sk)
    This event doesn't support event priority
    Line: on all BlockPlaceEvent with priority monitor:

**Server information**
- skript-reflect: 2.3
- Skript: 2.6.1
- Bukkit: Purpur
- Minecraft: 1.16.5
- Java: 17
- OS: Linux

**Comment by TPGamesNL** [comment]
Did you solve the issue?

**Comment by MisterLolxd2** [comment]
Yeah i'll find the fix in actions.
