### ISSUE TITLE
Can't listen for custom events

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/skript-reflect#68]
**Describe the bug**
When running with Skript 2.7.0-beta2, sections which listen for custom events no longer parse. This happens both on the initial load and on subsequent reloads of the script.

**To reproduce**
1. Create a custom event.
2. Write an event listener for your custom event (e.g., `on my custom event`).

**Expected behavior**
The handler should parse and should be fired when your custom event is fired.

**Screenshots**
Example with a minimalist server setup. See VS Code sidebar, Skript + skript-reflect are my only plugins (as well as the patcher agent).

![image](https://github.com/TPGamesNL/skript-reflect/assets/6902229/88393f4b-e1a2-4652-9f47-8dd89131a7c3)
![image](https://github.com/TPGamesNL/skript-reflect/assets/6902229/150aa959-78b5-42e3-8faf-5083c0ea8769)

**Server information**
- skript-reflect: 2.3.0
- Skript: 2.7.0-beta2
- Bukkit: 1.19.4 (running Purpur build 1968, for what that's worth)
- Minecraft: 1.19.4
- Java: 17.0.6
- OS: Windows 11

**Comment by TPGamesNL** [comment]
Fixed in https://github.com/TPGamesNL/skript-reflect/commit/0abbe26b580017d23a04398cd2a33c5b69908897
