### ISSUE TITLE
Can't call functions inside of custom syntax

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/skript-reflect#69]
**Describe the bug**
When running with Skript 2.7.0-beta2, function calls inside of custom syntax no longer parse. This happens both on the initial load and on subsequent reloads of the script. It does not matter if the function is in the same script or a different script, or whether or not it is local.

**To reproduce**
1. Create a function.
2. Create custom syntax.
3. Try to call that function within the custom syntax (e.g., `myExampleFunction()`).

**Expected behavior**
The function call should parse and should run when your custom syntax is triggered.

**Screenshots**
Example with a minimalist server setup. See VS Code sidebar, Skript + skript-reflect are my only plugins (as well as the patcher agent).

![image](https://github.com/TPGamesNL/skript-reflect/assets/6902229/6a6b17c1-0fa7-41bd-a005-19140339dd8f)
![image](https://github.com/TPGamesNL/skript-reflect/assets/6902229/4bbb15cb-804c-47a2-8ad6-956206eeff44)

**Server information**
- skript-reflect: 2.3.0
- Skript: 2.7.0-beta2
- Bukkit: 1.19.4 (running Purpur build 1968, for what that's worth)
- Minecraft: 1.19.4
- Java: 17.0.6
- OS: Windows 11

**Comment by L3v3lup** [comment]
I believe this is linked to the same problem here:
https://github.com/SkriptLang/Skript/issues/5779

With 1.20 released, this gets a bit more important.

**Comment by TPGamesNL** [comment]
Fix delayed at least until https://github.com/SkriptLang/Skript/pull/5669 is merged, as this PR finalizes the Structure API, which is what skript-reflect will be using.

**Comment by rudde0** [comment]
> Fix delayed at least until [SkriptLang/Skript#5669](https://github.com/SkriptLang/Skript/pull/5669) is merged, as this PR finalizes the Structure API, which is what skript-reflect will be using.

Could you fix it now?

**Comment by envizar** [comment]
> Fix delayed at least until [SkriptLang/Skript#5669](https://github.com/SkriptLang/Skript/pull/5669) is merged, as this PR finalizes the Structure API, which is what skript-reflect will be using.

@TPGamesNL  Will you fix this issue?

**Comment by TPGamesNL** [comment]
I will when I have time, i.e. not soon. Anyone is free to make a PR
