### ISSUE TITLE
Severe error when returning nothing from a custom property expression

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/skript-reflect#70]
**Describe the bug**
Custom property expressions cause a severe error when they return nothing (i.e., when using a plain `return`, or `return {_variable}` where `{_variable}` is unset).

This may be the case for other custom syntax too, but I've only noticed it with property expressions thus far in my 1.19.4 testing.

**To reproduce**
1. Create a custom property expression with returns nothing.
2. Call it.

**Expected behavior**
The property expression successfully returns an empty value (`<none>`).

**Screenshots**
Example with a minimalist server setup. See VS Code sidebar, Skript + skript-reflect are my only plugins (as well as the patcher agent).

![image](https://github.com/TPGamesNL/skript-reflect/assets/6902229/67edccea-5fd5-4121-a520-05a42c0080fd)
![image](https://github.com/TPGamesNL/skript-reflect/assets/6902229/e84ce8ae-1f3f-4386-8feb-f21d471ef27f)

**Server information**
skript-reflect: 2.3.0
Skript: 2.7.0-beta2
Bukkit: 1.19.4 (running Purpur build 1968, for what that's worth)
Minecraft: 1.19.4
Java: 17.0.6
OS: Windows 11

**Comment by TPGamesNL** [comment]
Fixed in https://github.com/TPGamesNL/skript-reflect/commit/3c668ba323a54bf7b0f6131bfbdf462d0b04c49d
