### ISSUE TITLE
Class is already mapped to another class, won't be remapped

### ISSUE THREAD

**Issue by 3meraldK** [SkriptLang/skript-reflect#74]
**Describe the bug**
There is a persistent error **message** when importing classes to a script, however it may be completely ignored as it causes no issues. 

**To reproduce**
```
import:
    org.bukkit.Bukkit
```

**Expected behavior**
No error messages, atleast after reloading again.

**Screenshots**
![image](https://github.com/TPGamesNL/skript-reflect/assets/48335651/911ac53b-6a4f-400b-a761-3562acdeab03)

**Server information**
- skript-reflect: 2.4-dev1
- Skript: 2.7-beta3 ([Fix enums build SkriptLang PR 5739](https://github.com/SkriptLang/Skript/suites/13556965305/artifacts/746097695))
- Bukkit: Paper 169
- Minecraft: 1.20.1
- Java: OpenJDK 17.0.8
- OS: Debian 12

**Additional context**
I don't like when `/sk reload scripts` throws 63 non-existent errors 😢

**Comment by envizar** [comment]
I fixed this in a very dumb way 
I removed line that creates this error
this is a temporary solution
Download: [skript-reflect-2.4-dev1.jar](https://cdn.discordapp.com/attachments/1140185095827881994/1150006770673139802/skript-reflect-2.4-dev1.jar)

**Comment by 3meraldK** [comment]
Fixed with latest [Skript 2.7.0](https://github.com/SkriptLang/Skript/releases/tag/2.7.0), latest [skript-reflect 2.3](https://github.com/TPGamesNL/skript-reflect/releases/tag/v2.3) (2.4-dev1 works too) **AND** [AddonPatcher](https://github.com/SkriptLang/AddonPatcher/releases/tag/2.7.0-dev1) (required fix)

**Comment by Shurelia** [comment]
i think this shouldnt be marked as completed as you'll need another addons to fix it
