### ISSUE TITLE
Two effects with same pattern cause exception - duplicate

### ISSUE THREAD

**Issue by ffddf111** [SkriptLang/skript-reflect#93]

**Comment by AyhamAl-Ali** [comment]
We need to know the custom structure that caused this error. Can you try reloading each script you have until that error appears again then send it or send the specific lines that causing it

**Comment by sovdeeth** [comment]
This error appears similar to #86 and another issue I encountered where parsing is interrupted by an error loading the methods of a class. Can you set your verbosity to very high, restart the server, and send latest.log?

**Comment by AyhamAl-Ali** [comment]
@cyclsunmark Even if it's fixed we would like to know what caused it and how you fixed it so we can fix it from our side as well :) can you share with us more info

**Comment by ffddf111** [comment]
import:
     me.clip.placeholderapi.PlaceholderAPI

expression placeholder %string% [from %offline player%]:
     get:
         return PlaceholderAPI.setPlaceholders(expr-2, "%%%expr-1%%%")

I was using this syntax in skript1.

in skript2

import:
     me.clip.placeholderapi.PlaceholderAPI

expression placeholder %string% [from %offline player%]:
     get:
         return PlaceholderAPI.setPlaceholders(expr-2, "%%%expr-1%%%")
This was a problem that arose while writing this again.
So expression placeholder %string% [from %offline player%]:
     get:
         return PlaceholderAPI.setPlaceholders(expr-2, "%%%expr-1%%%")

Since I deleted only this part, the error did not appear.

**Comment by AyhamAl-Ali** [comment]
Yes that seems to be same as #86. Thank you for the info.

**Comment by ffddf111** [comment]
When is it going to be fixed?
